In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('foodb_2020_04_07_csv/Content.csv')

/opt/anaconda3/envs/metis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (4,5,6,7,8,9,13,14,21,22,24) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [40]:
df.columns

Index(['id', 'source_id', 'source_type', 'food_id', 'orig_food_id',
       'orig_food_common_name', 'orig_food_scientific_name', 'orig_food_part',
       'orig_source_id', 'orig_source_name', 'orig_content', 'orig_min',
       'orig_max', 'orig_unit', 'orig_citation', 'citation', 'citation_type',
       'creator_id', 'updater_id', 'created_at', 'updated_at', 'orig_method',
       'orig_unit_expression', 'standard_content', 'preparation_type',
       'export'],
      dtype='object')

In [52]:
df.iloc[:, 20:30].head(20)

,updated_at,orig_method,orig_unit_expression,standard_content,preparation_type,export
0,2019-12-11 20:23:57 UTC,NaN,NaN,1955.00,raw,0
1,2019-12-11 20:23:57 UTC,NaN,NaN,1853.95,raw,0
2,2019-12-11 20:23:57 UTC,NaN,NaN,4150.00,raw,0
3,2019-12-11 20:23:57 UTC,NaN,NaN,3900.00,raw,0
4,2019-12-11 20:23:57 UTC,NaN,NaN,2500.00,other,0
5,2019-12-11 20:23:57 UTC,NaN,NaN,1300.00,other,0
6,2019-12-11 20:23:57 UTC,NaN,NaN,42600.00,other,0
7,2019-12-11 20:23:57 UTC,NaN,NaN,2188.60,raw,0
8,2019-12-11 20:23:57 UTC,NaN,NaN,4500.00,raw,0
9,2019-12-11 20:23:57 UTC,NaN,NaN,12410.00,raw,0
10,2019-12-11 20:23:57 UTC,NaN,NaN,1150.00,raw,0
11,2019-12-11 20:23:57 UTC,NaN,NaN,40000.00,raw,0
12,2019-12-11 20:23:57 UTC,NaN,NaN,NaN,raw,0
13,2019-12-11 20:23:57 UTC,NaN,NaN,2165.00,raw,0
14,2019-12-11 20:23:57 UTC,NaN,NaN,26110.65,raw,0
15,2019-12-11 20:23:57 UTC,NaN,NaN,1700.00,other,0
16,2019-12-11 20:23:57 UTC,NaN,NaN,5850.00,other,0
17,2019-12-11 20:23:57 UTC,NaN,NaN,36081.70,other,0
18,2019-12-11 20:23:57 UTC,NaN,NaN,16500.00,other (raw),0
19,2019-12-11 20:23:57 UTC,NaN,NaN,481.75,other (raw),0

In [58]:
df[df['preparation_type']=='beverage (Alcoholic)']

,id,source_id,source_type,food_id,orig_food_id,orig_food_common_name,orig_food_scientific_name,orig_food_part,orig_source_id,orig_source_name,...,citation_type,creator_id,updater_id,created_at,updated_at,orig_method,orig_unit_expression,standard_content,preparation_type,export
2487,2488,2,Nutrient,268,346,"Beer, danish household, low alcohol",NaN,NaN,0001,"Protein, total",...,DATABASE,NaN,NaN,2014-11-05 13:42:37 UTC,2019-12-11 20:24:08 UTC,NaN,NaN,300.00,beverage (Alcoholic),0
2488,2489,2,Nutrient,268,346,"Beer, danish household, low alcohol",NaN,NaN,0002,"Protein, total-N",...,DATABASE,NaN,NaN,2014-11-05 13:42:37 UTC,2019-12-11 20:24:08 UTC,NaN,NaN,0.00,beverage (Alcoholic),0
2489,2490,2,Nutrient,268,979,"Beer, danish household, low alcohol, average v...",NaN,NaN,0001,"Protein, total",...,DATABASE,NaN,NaN,2014-11-05 13:42:37 UTC,2019-12-11 20:24:08 UTC,NaN,NaN,300.00,beverage (Alcoholic),0
2490,2491,2,Nutrient,268,979,"Beer, danish household, low alcohol, average v...",NaN,NaN,0002,"Protein, total-N",...,DATABASE,NaN,NaN,2014-11-05 13:42:37 UTC,2019-12-11 20:24:08 UTC,NaN,NaN,0.00,beverage (Alcoholic),0
2491,2492,2,Nutrient,268,347,"Beer, export, alc. 5.6 % by vol.",NaN,NaN,0001,"Protein, total",...,DATABASE,NaN,NaN,2014-11-05 13:42:37 UTC,2019-12-11 20:24:08 UTC,NaN,NaN,400.00,beverage (Alcoholic),0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1741227,1802252,39,Nutrient,279,14037,"Alcoholic beverage, distilled, all (gin, rum, ...",NaN,NaN,NaN,NaN,...,DATABASE,NaN,NaN,2019-08-03 17:35:11 UTC,2019-08-03 17:35:11 UTC,NaN,NaN,0.01,beverage (Alcoholic),1
1741228,1802253,39,Nutrient,279,14037,"Alcoholic beverage, distilled, all (gin, rum, ...",NaN,NaN,NaN,NaN,...,DATABASE,NaN,NaN,2019-08-03 17:35:13 UTC,2019-08-03 17:35:13 UTC,NaN,NaN,0.01,beverage (Alcoholic),1
1741321,1802346,39,Nutrient,640,14052,"Alcoholic beverage, distilled, whiskey, 86 proof",NaN,NaN,NaN,NaN,...,DATABASE,NaN,NaN,2019-08-03 17:37:42 UTC,2019-08-03 17:37:42 UTC,NaN,NaN,0.00,beverage (Alcoholic),1
1741326,1802351,39,Nutrient,279,14037,"Alcoholic beverage, distilled, all (gin, rum, ...",NaN,NaN,NaN,NaN,...,DATABASE,NaN,NaN,2019-08-03 17:37:43 UTC,2019-08-03 17:37:43 UTC,NaN,NaN,0.00,beverage (Alcoholic),1
1741336,1802361,39,Nutrient,763,43479,"Alcoholic beverage, rice (sake)",NaN,NaN,NaN,NaN,...,DATABASE,NaN,NaN,2019-08-03 17:37:58 UTC,2019-08-03 17:37:58 UTC,NaN,NaN,0.00,beverage (Alcoholic),1

In [123]:
df[df['orig_food_part'] != 'NaN']["orig_food_part"].head(100)

0     Fruit
1      Bulb
2      Leaf
3      Leaf
4     Fruit
      ...
95     Seed
96     Seed
97    Fruit
98     Leaf
99     Seed
Name: orig_food_part, Length: 100, dtype: object

In [27]:
v_counts = df['orig_food_common_name'].value_counts()

In [38]:
len(v_counts[v_counts > 40])

7464

In [30]:
len(v_counts)

9460

In [23]:
foods = df.groupby(by='orig_food_common_name', as_index = True).count()

In [24]:
foods

,id,source_id,source_type,food_id,orig_food_id,orig_food_scientific_name,orig_food_part,orig_source_id,orig_source_name,orig_content,...,citation_type,creator_id,updater_id,created_at,updated_at,orig_method,orig_unit_expression,standard_content,preparation_type,export
orig_food_common_name,,,,,,,,,,,,,,,,,,,,,
(Capsicum anuum),1,1,1,1,0,0,0,0,0,1,...,1,0,0,1,1,0,0,1,0,1
(Cucumis melo),1,1,1,1,0,0,0,0,0,1,...,1,0,0,1,1,0,0,1,0,1
(Ipomoea batatas),1,1,1,1,0,0,0,0,0,1,...,1,0,0,1,1,0,0,1,0,1
(Lactuca sativa var. crispa),1,1,1,1,0,0,0,0,0,1,...,1,0,0,1,1,0,0,1,0,1
(Medicago sativa),1,1,1,1,0,0,0,0,0,1,...,1,0,0,1,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
steam-distilled onion oil,22,22,22,22,0,0,0,0,0,0,...,22,0,0,22,22,0,0,0,22,22
taco shell,41,41,41,41,0,0,0,0,0,39,...,41,0,0,41,41,0,0,39,0,41
tortilla flour,30,30,30,30,0,0,0,0,0,30,...,30,0,0,30,30,0,0,30,30,30
unsure,2,2,2,2,0,0,0,0,0,2,...,2,0,0,2,2,0,0,2,0,2
whole leaves of lettuce,59,59,59,59,0,0,0,0,0,0,...,59,0,0,59,59,0,0,0,59,59

 ``{'split','records','index',
        'columns','values', 'table'}``

In [155]:

import requests
from pandas.io.json import json_normalize
import pandas as pd
url='https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=178341'

#url='https://www.thecocktaildb.com/api/json/v1/1/filter.php?i=Gin'
#url = "https://www.thecocktaildb.com/api/json/v1/1/filter.php?a=Alcoholic"
drinks_data = pd.read_json(url)
drink_list = list(drinks_data["drinks"])
#print(drink_list)

ingredient_columns = ['strIngredient' + str(num) for num in range(1,16)]
#strIngredient1	strIngredient2	strIngredient3	strIngredient4	strIngredient5	strIngredient6	strIngredient7	strIngredient8	strIngredient9
drink_df = pd.DataFrame(drink_list)
drink_df[ingredient_columns]

,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15
0,Gin,Orange Juice,Lemon Juice,Rosemary Syrup,Soda Water,Rosemary,Orange Peel,None,None,None,None,None,None,None,None

In [113]:
drink_list = []
for row in json_df.iterrows():
    #print(row)
    #print(type(row))
    n, dic = row
    drink_list.append(dic)

#drink_list[0]
n

99

In [100]:
import requests
import json
import webbrowser

c_df = pd.DataFrame()

def cocktails():
    f = r"https://www.thecocktaildb.com/api/json/v1/1/filter.php?c=Cocktail"
    data = requests.get(f)
    tt = json.loads(data.text)
    #webbrowser.open(tt["url"])
    c_df = pd.DataFrame(tt)
    for i in (tt["drinks"]):
        pass
        #print(i, "\n")
    #print(len(tt["drinks"]))    
cocktails()

c_df.head()

Empty DataFrame
Columns: []
Index: []

In [111]:
import json  
import pandas as pd  
from pandas.io.json import json_normalize  

url = "https://www.thecocktaildb.com/api/json/v1/1/filter.php?c=Cocktail"

with open(url) as f: 
    d = json.load(f) 

 

# lets put the data into a pandas df 
# clicking on raw_nyc_phil.json under "Input Files" 
# tells us parent node is 'programs' 
df_cocktails = json_normalize(d['cocktails']) 
df_cocktails.head(3)

FileNotFoundError: [Errno 2] No such file or directory: 'https://www.thecocktaildb.com/api/json/v1/1/filter.php?c=Cocktail'

In [102]:
import requests
import json
import webbrowser
def cocktails():
    f = r"https://www.thecocktaildb.com/api/json/v1/1/filter.php?i=Gin"
    data = requests.get(f)
    tt = json.loads(data.text)
    print(tt)
    
    for i in (tt["drinks"]):
        try:
            url = i["strDrinkThumb"]
            #webbrowser.open(url)
            print(i, "\n")
            print(i["strDrink"], "\n")
        except Exception:
            pass
cocktails()

{'drinks': [{'strDrink': '3-Mile Long Island Iced Tea', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rrtssw1472668972.jpg', 'idDrink': '15300'}, {'strDrink': '69 Special', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vqyxqx1472669095.jpg', 'idDrink': '13940'}, {'strDrink': 'A1', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg', 'idDrink': '17222'}, {'strDrink': 'Abbey Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/mr30ob1582479875.jpg', 'idDrink': '17834'}, {'strDrink': 'Abbey Martini', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2mcozt1504817403.jpg', 'idDrink': '17223'}, {'strDrink': 'Ace', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg', 'idDrink': '17225'}, {'strDrink': 'Adam & Eve', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vfeumw1504819077.jpg', 'idDrink': '17226'}, {'strDrink': 'Addison', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yzva7x1504820300.jpg', 'idDrink': '17228'}, {'strDrink': 'Alaska Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wsyryt1483387720.jpg', 'idDrink': '11013'}, {'strDrink': 'Alexander', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/0clus51606772388.jpg', 'idDrink': '11014'}, {'strDrink': 'Allies Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qvprvp1483388104.jpg', 'idDrink': '11022'}, {'strDrink': 'Angel Face', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vaukir1606772580.jpg', 'idDrink': '11034'}, {'strDrink': 'Archbishop', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/4g6xds1582579703.jpg', 'idDrink': '11052'}, {'strDrink': 'Army special', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/55muhh1493068062.jpg', 'idDrink': '17066'}, {'strDrink': 'Arthur Tompkins', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/7onfhz1493067921.jpg', 'idDrink': '11054'}, {'strDrink': 'Artillery', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/g1vnbe1493067747.jpg', 'idDrink': '11055'}, {'strDrink': 'AT&T', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg', 'idDrink': '13938'}, {'strDrink': 'Aviation', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/trbplb1606855233.jpg', 'idDrink': '17180'}, {'strDrink': 'Bermuda Highball', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qrvtww1441206528.jpg', 'idDrink': '11084'}, {'strDrink': 'Bijou', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rysb3r1513706985.jpg', 'idDrink': '17254'}, {'strDrink': 'Bluebird', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/5jhyd01582579843.jpg', 'idDrink': '11120'}, {'strDrink': 'Bombay Cassis', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/h1e0e51510136907.jpg', 'idDrink': '17242'}, {'strDrink': 'Boomerang', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/3m6yz81504389551.jpg', 'idDrink': '11124'}, {'strDrink': 'Boxcar', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/pwgtpa1504366376.jpg', 'idDrink': '11149'}, {'strDrink': 'Bramble', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/lvzl3r1504372526.jpg', 'idDrink': '17210'}, {'strDrink': 'Casino', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/1mvjxg1504348579.jpg', 'idDrink': '17185'}, {'strDrink': 'Casino Royale', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/3qpv121504366699.jpg', 'idDrink': '11224'}, {'strDrink': 'Cherry Electric Lemonade', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tquyyt1451299548.jpg', 'idDrink': '17174'}, {'strDrink': 'Clover Club', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/t0aja61504348715.jpg', 'idDrink': '17186'}, {'strDrink': 'Corpse Reviver #2', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/gifgao1513704334.jpg', 'idDrink': '17250'}, {'strDrink': 'Derby', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/52weey1606772672.jpg', 'idDrink': '17187'}, {'strDrink': 'Dragonfly', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/uc63bh1582483589.jpg', 'idDrink': '11320'}, {'strDrink': 'Dry Martini', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg', 'idDrink': '11005'}, {'strDrink': 'Dubonnet Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/pfz3hz1582483111.jpg', 'idDrink': '11326'}, {'strDrink': 'English Highball', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/dhvr7d1504519752.jpg', 'idDrink': '11338'}, {'strDrink': 'English Rose Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yxwrpp1441208697.jpg', 'idDrink': '11339'}, {'strDrink': 'Flying Dutchman', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/mwko4q1582482903.jpg', 'idDrink': '11368'}, {'strDrink': 'French 75', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/hrxfbl1606773109.jpg', 'idDrink': '17197'}, {'strDrink': 'French Negroni', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/x8lhp41513703167.jpg', 'idDrink': '17248'}, {'strDrink': 'Garibaldi Negroni', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/kb4bjg1604179771.jpg', 'idDrink': '178340'}, {'strDrink': "Gentleman's Club", 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/k2r7wv1582481454.jpg', 'idDrink': '11396'}, {'strDrink': 'Gimlet', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/3xgldt1513707271.jpg', 'idDrink': '17255'}, {'strDrink': 'Gin and Soda', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/nzlyc81605905755.jpg', 'idDrink': '178342'}, {'strDrink': 'Gin And Tonic', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/z0omyp1582480573.jpg', 'idDrink': '11403'}, {'strDrink': 'Gin Basil Smash', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/jqh2141572807327.jpg', 'idDrink': '178314'}, {'strDrink': 'Gin Cooler', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/678xt11582481163.jpg', 'idDrink': '11407'}, {'strDrink': 'Gin Daisy', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/z6e22f1582581155.jpg', 'idDrink': '11408'}, {'strDrink': 'Gin Fizz', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/drtihp1606768397.jpg', 'idDrink': '11410'}, {'strDrink': 'Gin Rickey', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/s00d6f1504883945.jpg', 'idDrink': '17230'}, {'strDrink': 'Gin Sling', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/8cl9sm1582581761.jpg', 'idDrink': '11415'}, {'strDrink': 'Gin Smash', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/iprva61606768774.jpg', 'idDrink': '11416'}, {'strDrink': 'Gin Sour', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/noxp7e1606769224.jpg', 'idDrink': '11417'}, {'strDrink': 'Gin Squirt', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xrbhz61504883702.jpg', 'idDrink': '11418'}, {'strDrink': 'Gin Swizzle', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/sybce31504884026.jpg', 'idDrink': '11419'}, {'strDrink': 'Gin Toddy', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/jxstwf1582582101.jpg', 'idDrink': '11420'}, {'strDrink': 'Grass Skirt', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qyvprp1473891585.jpg', 'idDrink': '11433'}, {'strDrink': 'Hawaiian Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ujoh9x1504882987.jpg', 'idDrink': '11472'}, {'strDrink': 'Imperial Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/bcsj2e1487603625.jpg', 'idDrink': '12706'}, {'strDrink': 'Jewel Of The Nile', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/hx4nrb1504884947.jpg', 'idDrink': '11566'}, {'strDrink': 'Jitterbug', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wwqvrq1441245318.jpg', 'idDrink': '16178'}, {'strDrink': 'Lady Love Fizz', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/20d63k1504885263.jpg', 'idDrink': '11634'}, {'strDrink': 'London Town', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rpsrqv1468923507.jpg', 'idDrink': '11662'}, {'strDrink': 'Lone Tree Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tsxpty1468923417.jpg', 'idDrink': '11664'}, {'strDrink': 'Lone Tree Cooler', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wsyqry1479298485.jpg', 'idDrink': '11666'}, {'strDrink': 'Long Island Tea', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/nkwr4c1606770558.jpg', 'idDrink': '11002'}, {'strDrink': 'Martinez 2', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/fs6kiq1513708455.jpg', 'idDrink': '17256'}, {'strDrink': 'Martinez Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wwxwvr1439906452.jpg', 'idDrink': '11720'}, {'strDrink': 'Martini', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/71t8581504353095.jpg', 'idDrink': '11728'}, {'strDrink': 'Monkey Gland', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/94psp81504350690.jpg', 'idDrink': '17189'}, {'strDrink': 'Munich Mule', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rj55pl1582476101.jpg', 'idDrink': '178315'}, {'strDrink': 'National Aquarium', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/dlw0om1503565021.jpg', 'idDrink': '13192'}, {'strDrink': 'Negroni', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qgdu971561574065.jpg', 'idDrink': '11003'}, {'strDrink': 'Orange Oasis', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/su1olx1582473812.jpg', 'idDrink': '11870'}, {'strDrink': 'Orange Rosemary Collins', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/mokcas1604179977.jpg', 'idDrink': '178341'}, {'strDrink': 'Paradise', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ejozd71504351060.jpg', 'idDrink': '17190'}, {'strDrink': 'Pegu Club', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/jfkemm1513703902.jpg', 'idDrink': '17249'}, {'strDrink': 'Pink Gin', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qyr51e1504888618.jpg', 'idDrink': '11936'}, {'strDrink': 'Pink Lady', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/5ia6j21504887829.jpg', 'idDrink': '11938'}, {'strDrink': 'Poppy Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/cslw1w1504389915.jpg', 'idDrink': '11959'}, {'strDrink': 'Queen Elizabeth', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vpqspv1478963339.jpg', 'idDrink': '11991'}, {'strDrink': 'Rose', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/8kxbvq1504371462.jpg', 'idDrink': '17208'}, {'strDrink': 'Rosemary Blue', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qwc5f91512406543.jpg', 'idDrink': '17245'}, {'strDrink': 'Royal Fizz', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wrh44j1504390609.jpg', 'idDrink': '12055'}, {'strDrink': 'Royal Gin Fizz', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/pe1x1c1504735672.jpg', 'idDrink': '12057'}, {'strDrink': 'Ruby Tuesday', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qsyqqq1441553437.jpg', 'idDrink': '17114'}, {'strDrink': 'Salted Toffee Martini', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/3s6mlr1509551211.jpg', 'idDrink': '17233'}, {'strDrink': 'Salty Dog', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/4vfge01504890216.jpg', 'idDrink': '12107'}, {'strDrink': 'Singapore Sling', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/7dozeg1582578095.jpg', 'idDrink': '12214'}, {'strDrink': 'Surf City Lifesaver', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2rzfer1487602699.jpg', 'idDrink': '12760'}, {'strDrink': 'The Laverstoke', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/6xfj5t1517748412.jpg', 'idDrink': '17824'}, {'strDrink': 'The Philosopher', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/sp8hkp1596017787.jpg', 'idDrink': '178330'}, {'strDrink': 'The Strange Weaver', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/opxjzh1604179528.jpg', 'idDrink': '178339'}, {'strDrink': 'Tom Collins', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/7cll921606854636.jpg', 'idDrink': '12402'}, {'strDrink': 'Turf Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/utypqq1441554367.jpg', 'idDrink': '12418'}, {'strDrink': 'Tuxedo Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/4u0nbl1504352551.jpg', 'idDrink': '12420'}, {'strDrink': 'Vesper', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/mtdxpa1504374514.jpg', 'idDrink': '17218'}, {'strDrink': 'Victor', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/voapgc1492976416.jpg', 'idDrink': '12450'}, {'strDrink': 'Waikiki Beachcomber', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ysuqus1441208583.jpg', 'idDrink': '12474'}, {'strDrink': 'White Lady', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/jofsaz1504352991.jpg', 'idDrink': '17194'}]}
{'strDrink': '3-Mile Long Island Iced Tea', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rrtssw1472668972.jpg', 'idDrink': '15300'}

3-Mile Long Island Iced Tea

{'strDrink': '69 Special', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vqyxqx1472669095.jpg', 'idDrink': '13940'}

69 Special

{'strDrink': 'A1', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg', 'idDrink': '17222'}

A1

{'strDrink': 'Abbey Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/mr30ob1582479875.jpg', 'idDrink': '17834'}

Abbey Cocktail

{'strDrink': 'Abbey Martini', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2mcozt1504817403.jpg', 'idDrink': '17223'}

Abbey Martini

{'strDrink': 'Ace', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg', 'idDrink': '17225'}

Ace

{'strDrink': 'Adam & Eve', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vfeumw1504819077.jpg', 'idDrink': '17226'}

Adam & Eve

{'strDrink': 'Addison', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yzva7x1504820300.jpg', 'idDrink': '17228'}

Addison

{'strDrink': 'Alaska Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wsyryt1483387720.jpg', 'idDrink': '11013'}

Alaska Cocktail

{'strDrink': 'Alexander', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/0clus51606772388.jpg', 'idDrink': '11014'}

Alexander

{'strDrink': 'Allies Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qvprvp1483388104.jpg', 'idDrink': '11022'}

Allies Cocktail

{'strDrink': 'Angel Face', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vaukir1606772580.jpg', 'idDrink': '11034'}

Angel Face

{'strDrink': 'Archbishop', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/4g6xds1582579703.jpg', 'idDrink': '11052'}

Archbishop

{'strDrink': 'Army special', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/55muhh1493068062.jpg', 'idDrink': '17066'}

Army special

{'strDrink': 'Arthur Tompkins', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/7onfhz1493067921.jpg', 'idDrink': '11054'}

Arthur Tompkins

{'strDrink': 'Artillery', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/g1vnbe1493067747.jpg', 'idDrink': '11055'}

Artillery

{'strDrink': 'AT&T', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg', 'idDrink': '13938'}

AT&T

{'strDrink': 'Aviation', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/trbplb1606855233.jpg', 'idDrink': '17180'}

Aviation

{'strDrink': 'Bermuda Highball', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qrvtww1441206528.jpg', 'idDrink': '11084'}

Bermuda Highball

{'strDrink': 'Bijou', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rysb3r1513706985.jpg', 'idDrink': '17254'}

Bijou

{'strDrink': 'Bluebird', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/5jhyd01582579843.jpg', 'idDrink': '11120'}

Bluebird

{'strDrink': 'Bombay Cassis', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/h1e0e51510136907.jpg', 'idDrink': '17242'}

Bombay Cassis

{'strDrink': 'Boomerang', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/3m6yz81504389551.jpg', 'idDrink': '11124'}

Boomerang

{'strDrink': 'Boxcar', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/pwgtpa1504366376.jpg', 'idDrink': '11149'}

Boxcar

{'strDrink': 'Bramble', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/lvzl3r1504372526.jpg', 'idDrink': '17210'}

Bramble

{'strDrink': 'Casino', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/1mvjxg1504348579.jpg', 'idDrink': '17185'}

Casino

{'strDrink': 'Casino Royale', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/3qpv121504366699.jpg', 'idDrink': '11224'}

Casino Royale

{'strDrink': 'Cherry Electric Lemonade', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tquyyt1451299548.jpg', 'idDrink': '17174'}

Cherry Electric Lemonade

{'strDrink': 'Clover Club', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/t0aja61504348715.jpg', 'idDrink': '17186'}

Clover Club

{'strDrink': 'Corpse Reviver #2', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/gifgao1513704334.jpg', 'idDrink': '17250'}

Corpse Reviver #2

{'strDrink': 'Derby', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/52weey1606772672.jpg', 'idDrink': '17187'}

Derby

{'strDrink': 'Dragonfly', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/uc63bh1582483589.jpg', 'idDrink': '11320'}

Dragonfly

{'strDrink': 'Dry Martini', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg', 'idDrink': '11005'}

Dry Martini

{'strDrink': 'Dubonnet Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/pfz3hz1582483111.jpg', 'idDrink': '11326'}

Dubonnet Cocktail

{'strDrink': 'English Highball', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/dhvr7d1504519752.jpg', 'idDrink': '11338'}

English Highball

{'strDrink': 'English Rose Cocktail', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yxwrpp1441208697.jpg', 'idDrink': '11339'}

English Rose Cocktail

{'strDrink': 'Flying Dutchman', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/mwko4q1582482903.jpg', 'idDrink': '11368'}

Flying Dutchman

{'strDrink': 'French 75', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/hrxfbl1606773109.jpg', 'idDrink': '17197'}

French 75

{'strDrink': 'French Negroni', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/x8lhp41513703167.jpg', 'idDrink': '17248'}

French Negroni

{'strDrink': 'Garibaldi Negroni', 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/kb4bjg1604179771.jpg', 'idDrink': '178340'}
